### ISSUE TITLE
Nested range causes false positive "Range statement [..] does not reinitialise the variable"

### ISSUE THREAD

**Issue by prashantv** [kunwardeep/paralleltest#12]
Repro:
https://gist.github.com/prashantv/9febe96e7df2b0d5311fa3b4aedb3059

Using the latest release of paralleltest (1.0.3) raises an incorrect issue:
```
[...]/foo_test.go:27:2: Range statement for test TestFoo does not reinitialise the variable tt2
```

`tt2` is reinitialized:
https://gist.github.com/prashantv/9febe96e7df2b0d5311fa3b4aedb3059#file-foo_test-go-L31

This seems related to https://github.com/kunwardeep/paralleltest/issues/8 (though the last comment on the issue indicates the issue is fixed)

**Comment by kunwardeep** [comment]
Hey @prashantv, unfortunately, I am not doing active development on this., but I would be more than happy to look at a PR if you have one.

**Comment by kunwardeep** [comment]
Hey @prashantv would you be able to test this with the latest fix?
