### ISSUE TITLE
Mode to only report invalid uses of t.Parallel, but not missing ones

### ISSUE THREAD

**Issue by turbolent** [kunwardeep/paralleltest#16]
Is there a way to lint code to only detect invalid uses of `t.Parallel`, but ignore opportunities to add `t.Parallel`?

We would like to just check for https://github.com/kunwardeep/paralleltest#tparallel-is-called-in-the-range-method-and-test-case-variable-tc-being-used-but-is-not-reinitialised-more-info in particular.

I'd be happy to open a PR for that.

**Comment by kunwardeep** [comment]
Having that option would be awesome, @turbolent. But I think to do that, we would need a way to pass in some options. The default case would be `detect invalid uses and opportunities to add t.Parallel` and then we can pass in flags to ignore the `ignore opportunities to add t.Parallel`. What do you think?

**Comment by turbolent** [comment]
@kunwardeep Sounds good! I've written an analyzer before, but have to look into how options can be passed. 

Ideally we would want the option to be a setting which could be passed into golangci-lint (https://golangci-lint.run/usage/linters/#linters-configuration)

**Comment by kunwardeep** [comment]
That sounds perfect.
