### ISSUE TITLE
False positive on tests in go 1.22 / 1.21 w/ GOEXPERIMENT=loopvar

### ISSUE THREAD

**Issue by pkwarren** [kunwardeep/paralleltest#34]
In Go 1.22 (with `GOEXPERIMENT=loopvar` now the default), the `Range statement for test <test> does not reinitialise the variable <var>` linter is no longer accurate. If you take the example program linked from https://github.com/kunwardeep/paralleltest?tab=readme-ov-file#tparallel-is-called-in-the-range-method-and-test-case-variable-tc-being-used-but-is-not-reinitialised-more-info, you can see that it no longer reports incorrect output.

Is it possible to omit these warnings when running on Go 1.22+ or allow a mechanism to ignore these warnings?

**Comment by kunwardeep** [comment]
Hey @pkwarren, thanks for bringing this to my attention. Any chance you could submit a PR?
