### ISSUE TITLE
Any Run(...) call is assumed to be t.Run

### ISSUE THREAD

**Issue by rkennedy** [kunwardeep/paralleltest#9]
The function I'm testing happens to be named `Run`. When I call it twice in a test function, parallleltest flags them as missing calls to `Parallel` even though they're not calling the `Run` function from the testing module.

```go
type foo int
func (foo) Run() {}
func TestFooRunning(t *testing.T) {
    t.Parallel()
    var x foo
    x.Run()
    x.Run()
}
```

Both calls to `Run` are flagged: "Function TestFooRunning has missing the call to method parallel in the test run"

**Comment by MyChaOS87** [comment]
I have the same issue
any chance to see this merged?
